# Generated by Django 4.1.4 on 2022-12-29 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateField(default=datetime.datetime(2022, 12, 29, 4, 32, 57, 208966, tzinfo=datetime.timezone.utc))),
                ('date_to', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
